name: Deploy Website with SSH Password

on:
  push:
    branches: [ main ]  # 替换为你的主分支名称
  workflow_dispatch:    # 允许手动触发

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史

      # 安装sshpass
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
        
      # 使用sshpass和rsync部署文件
      - name: Deploy with rsync using password
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          # 添加服务器到known_hosts以避免确认提示
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT || 22 }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
          # 使用sshpass进行rsync
          sshpass -e rsync -avz --delete \
            -e "ssh -p ${{ secrets.SSH_PORT || 22 }}" \
            ./ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.REMOTE_PATH }}/
            
      # 设置正确的文件权限
      - name: Set correct permissions
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -e ssh -p ${{ secrets.SSH_PORT || 22 }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "sudo chown -R safeline:safeline ${{ secrets.REMOTE_PATH }}/"
          
      # 通知部署完成
      - name: Notify deployment completion
        run: |
          echo "Website successfully deployed to ${{ secrets.SSH_HOST }}:${{ secrets.REMOTE_PATH }} at $(date)"
